apiVersion: catalog.onefootball.com/v1alpha1
kind: Metric
metadata:
  name: alert-routing-and-notifications
spec:
  description: https://github.com/motain/of-catalog/blob/main/docs/grading-system/observability.md#alert-routing-and-notifications
  format:
    unit: Critical Alerts/SLO Check
  name: alert-routing-and-notifications
  grading-system: observability
  cronSchedule: "0 * * * *"
  componentType:
    - service
  facts:
    - auth:
        header: X-Honeycomb-Team
        tokenVar: HONEYCOMB_API_KEY
      id: fetch-slos
      jsonPath: .[].id
      name: Fetch SLOs
      rule: jsonpath
      source: jsonapi
      type: extract
      uri: https://api.eu1.honeycomb.io/1/slos/${Metadata.Name}
    - auth:
        header: X-Honeycomb-Team
        tokenVar: HONEYCOMB_API_KEY
      dependsOn:
        - fetch-slos
      id: fetch-alerts-for-slos
      jsonPath: .[].id
      name: Fetch alerts for SLOs
      rule: jsonpath
      source: jsonapi
      type: extract
      uri: https://api.eu1.honeycomb.io/1/burn_alerts/${Metadata.Name}?slo_id=:slo_id
    - auth:
        header: X-Honeycomb-Team
        tokenVar: HONEYCOMB_API_KEY
      dependsOn:
        - fetch-alerts-for-slos
      id: fetch-recipients-for-alerts
      jsonPath: .recipients[].target
      name: Fetch recipients for Alerts
      rule: jsonpath
      source: jsonapi
      type: extract
      uri: https://api.eu1.honeycomb.io/1/burn_alerts/${Metadata.Name}/:alert_id
    - dependsOn:
        - fetch-recipients-for-alerts
      id: validate-each-target-is-not-empty-string
      name: Validate that each target is not an empty string
      pattern: ^\S.*$
      rule: regex_match
      type: validate
    - dependsOn:
        - validate-each-target-is-not-empty-string
      id: validate-all-targets-are-not-empty-strings
      method: and
      name: Validate that all targets are not empty strings
      type: aggregate