apiVersion: catalog.onefootball.com/v1alpha1
kind: Metric
metadata:
  name: critical-alerts-slo-check
spec:
  description: https://github.com/motain/of-catalog/blob/main/docs/grading-system/observability.md#critical-alerts-slo-check
  format:
    unit: Critical Alerts/SLO Check
  name: critical-alerts-slo-check
  cronSchedule: "0 * * * *"
  facts:
    - auth:
        header: X-Honeycomb-Team
        tokenVar: HONEYCOMB_API_KEY
      id: fetch-slos
      jsonPath: .[].id
      name: Fetch SLOs
      rule: jsonpath
      source: jsonapi
      type: extract
      uri: https://api.eu1.honeycomb.io/1/slos/${Metadata.Name}
    - auth:
        header: X-Honeycomb-Team
        tokenVar: HONEYCOMB_API_KEY
      dependsOn:
        - fetch-slos
      id: fetch-alerts-for-slos
      jsonPath: .[].id
      name: Fetch alerts for SLOs
      rule: jsonpath
      source: jsonapi
      type: extract
      uri: https://api.eu1.honeycomb.io/1/burn_alerts/${Metadata.Name}?slo_id=:slo_id
    - dependsOn:
        - fetch-slos
      id: count-slos
      method: count
      name: Count SLOs
      type: aggregate
    - dependsOn:
        - fetch-alerts-for-slos
      id: count-alerts-for-slos
      method: count
      name: Count Alerts
      type: aggregate
    - dependsOn:
        - count-slos
        - count-alerts-for-slos
      id: validate-alerts-for-slos
      name: Validate that counts match
      rule: deps_match
      type: validate
  grading-system: observability
  componentType:
    - service