apiVersion: catalog.onefootball.com/v1alpha1
kind: Metric
metadata:
  name: deployment-readiness
spec:
  description: https://github.com/motain/of-catalog/blob/main/docs/grading-system/production-readiness.md#deployment-readiness
  format:
    unit: Deployment Standards
  name: deployment-readiness
  facts:
    - filePath: app.toml
      id: deployment-readiness-replicas-service-production
      jsonPath: (.service.production.replicas_min != .service.production.replicas_max)
        and (.service.production.replicas_min >= 3) and (.service.production.replicas_max
        > 3)
      name: Check deployment readiness where min != Max, Min >= 3 and Max > 3
      repo: ${Metadata.Name}
      rule: jsonpath
      source: github
      type: extract
    - filePath: app.toml
      id: deployment-readiness-replicas-service
      jsonPath: (.service.replicas_min != .service.replicas_max) and (.service.replicas_min
        >= 3) and (.service.replicas_max > 3)
      name: Check deployment readiness where min != Max, Min >= 3 and Max > 3
      repo: ${Metadata.Name}
      rule: jsonpath
      source: github
      type: extract
    - dependsOn:
        - deployment-readiness-replicas-service-production
        - deployment-readiness-replicas-service
      id: aggregate-replicas
      method: or
      name: Check deployment readiness where min != Max, Min >= 3 and Max > 3
      type: aggregate
  componentType:
    - service
    - cloud-resource
  grading-system: production-readiness
  cronSchedule: "0 * * * *"