apiVersion: metacontroller.k8s.io/v1alpha1
kind: CompositeController
metadata:
  name: metrics-controller
spec:
  parentResource:
    apiVersion: catalog.onefootball.com/v1alpha1
    resource: metrics
  childResources:
    - apiVersion: batch/v1
      resource: cronjobs
      updateStrategy:
        method: OnDelete
  resyncPeriodSeconds: 600
  generateSelector: true
  hooks:
    sync:
      webhook:
        url: http://catalog-controller.catalog-controller.svc.cluster.local/sync/metric
        timeout: 600s
    finalize:
      webhook:
        url: http://catalog-controller.catalog-controller.svc.cluster.local/finalize/metric
        timeout: 600s
---
apiVersion: catalog.onefootball.com/v1alpha1
kind: Metric
metadata:
  generation: 1
  name: allocation-efficiency
spec:
  componentType:
    - service
    - cloud-resource
  cronSchedule: 0 * * * *
  description: >-
    https://github.com/motain/of-catalog/blob/main/docs/grading-system/cost-optimization.md#cost-optimization-grading-system
  evaluateOnDeploy: false
  facts:
    - filePath: app.toml
      id: check-app-toml-resource-request
      jsonPath: >-
        (.service.cpu_requests // .service.production.cpu_requests | . != null)
        and (.service.memory_requests // .service.production.memory_requests | .
        != null)
      name: >-
        Check if CPU requests and memory requests are defined in app.toml under
        [service] or [service.production]
      repo: ${Metadata.Name}
      rule: jsonpath
      source: github
      type: extract
    - filePath: app.toml
      id: check-app-toml-cpu-limits
      jsonPath: .service.cpu_limits // .service.production.cpu_limits | not
      name: >-
        Check if CPU limits are not defined in app.toml under [service] or
        [service.production]
      repo: ${Metadata.Name}
      rule: jsonpath
      source: github
      type: extract
    - filePath: app.toml
      id: check-app-toml-memory-limits
      jsonPath: .service.memory_limits // .service.production.memory_limits | . != null
      name: >-
        Check if  memory limits are defined in app.toml under [service] or
        [service.production]
      repo: ${Metadata.Name}
      rule: jsonpath
      source: github
      type: extract
    - dependsOn:
        - check-app-toml-resource-request
        - check-app-toml-cpu-limits
        - check-app-toml-memory-limits
      id: aggregate-resource-requests
      method: and
      name: check resource requests and limits
      type: aggregate
  format:
    unit: Allocation Efficiency
  grading-system: cost-optimization
  name: allocation-efficiency
