apiVersion: catalog.onefootball.com/v1alpha1
kind: Scorecard
metadata:
  name: sample
spec:
  componentTypeIds:
  - SERVICE
  criteria:
  - hasMetricValue:
      comparator: EQUALS
      comparatorValue: 1
      metricName: instrumentation-check
      name: instrumentation-check
      weight: 15
  - hasMetricValue:
      comparator: EQUALS
      comparatorValue: 1
      metricName: critical-alerts-slo-check
      name: critical-alerts-slo-check
      weight: 15
  - hasMetricValue:
      comparator: EQUALS
      comparatorValue: 1
      metricName: alert-routing-and-notifications
      name: alert-routing-and-notifications
      weight: 45
  - hasMetricValue:
      comparator: EQUALS
      comparatorValue: 1
      metricName: observability-documentation
      name: observability-documentation
      weight: 25
  description: https://github.com/motain/of-catalog/blob/main/docs/grading-system/observability.md#observability-grading-system
  importance: REQUIRED
  name: sample
  ownerId: 712020:edcf2690-1f3e-4310-9eb8-1ecef88d64b6
  scoringStrategyType: WEIGHT_BASED
  state: PUBLISHED
