apiVersion: catalog.onefootball.com/v1alpha1
kind: Scorecard
metadata:
  name: cost-optimization
spec:
  componentTypeIds:
  - SERVICE
  criteria:
  - hasMetricValue:
      comparator: EQUALS
      comparatorValue: 1
      metricName: allocation-efficiency
      name: allocation-efficiency
      weight: 100
  description: https://github.com/motain/of-catalog/blob/main/docs/grading-system/cost-optimization.md#cost-optimization-grading-system
  importance: REQUIRED
  name: cost-optimization
  ownerId: 712020:edcf2690-1f3e-4310-9eb8-1ecef88d64b6
  scoringStrategyType: WEIGHT_BASED
  state: PUBLISHED
