apiVersion: catalog.onefootball.com/v1alpha1
kind: Scorecard
metadata:
  name: production-readiness
spec:
  componentTypeIds:
  - SERVICE
  criteria:
  - hasMetricValue:
      comparator: EQUALS
      comparatorValue: 1
      metricName: organizational-standards
      name: organizational-standards
      weight: 50
  - hasMetricValue:
      comparator: EQUALS
      comparatorValue: 1
      metricName: deployment-readiness
      name: deployment-readiness
      weight: 50
  description: https://github.com/motain/of-catalog/blob/main/docs/grading-system/production-readiness.md#production-readiness-grading-system
  importance: REQUIRED
  name: production-readiness
  ownerId: 712020:edcf2690-1f3e-4310-9eb8-1ecef88d64b6
  scoringStrategyType: WEIGHT_BASED
  state: PUBLISHED
