apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRoleBinding
metadata:
  name: {{ include "catalog-controller.fullname" . }}-binding
  labels:
    {{- include "catalog-controller.labels" . | nindent 4 }}
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: ClusterRole
  name: {{ include "catalog-controller.fullname" . }}-role
subjects:
  - kind: ServiceAccount
    name: {{ include "catalog-controller.serviceAccountName" . }}
    namespace: {{ include "catalog-controller.fullname" . }}
