{{- range .Values.controllers }}
---
apiVersion: metacontroller.k8s.io/v1alpha1
kind: CompositeController
metadata:
  name: {{ .resource }}-controller
spec:
  parentResource:
    apiVersion: catalog.onefootball.com/v1alpha1
    resource: {{ .resource }}
  {{- if .children }} # Only include children if defined
  childResources:
  {{- range .children }}
    - apiVersion: {{ .apiVersion }}
      resource: {{ .resource }}
      updateStrategy:
        method: InPlace
  {{- end }}
  {{- end }}
  resyncPeriodSeconds: {{ .resyncPeriod }}
  generateSelector: true
  hooks:
    sync:
      webhook:
        url: http://{{ .service }}{{ .sync.path }}
        timeout: {{ .sync.timeout }}
    finalize:
      webhook:
        url: http://{{ .service }}{{ .finalizer.path }}
        timeout: {{ .finalizer.timeout }}
{{- end }}
