apiVersion: catalog.onefootball.com/v1alpha1
kind: Metric
metadata:
  name: instrumentation-check
spec:
  description: https://github.com/motain/of-catalog/blob/main/docs/grading-system/observability.md#instrumentation-check
  format:
    unit: Instrumentation Check
  name: instrumentation-check
  cronSchedule: "0 * * * *"
  facts:
    - auth: null
      filePath: app.toml
      id: read-otel-service-name-from-apptoml
      jsonPath: .envs.OTEL_SERVICE_NAME // .envs.production.OTEL_SERVICE_NAME // .service.production.envs.OTEL_SERVICE_NAME
        // .service.envs.OTEL_SERVICE_NAME
      name: Read OTEL_SERVICE_NAME from app.toml
      repo: ${Metadata.Name}
      rule: jsonpath
      source: github
      type: extract
    - dependsOn:
        - read-otel-service-name-from-apptoml
      id: validate-otel-service-name-matches-component-name
      name: validate OTEL_SERVICE_NAME matches component name
      pattern: ^${Metadata.Name}.*$
      rule: regex_match
      type: validate
    - auth: null
      filePath: app.toml
      id: read-otel-resource-attributes-from-apptoml
      jsonPath: .envs.OTEL_RESOURCE_ATTRIBUTES // .envs.production.OTEL_RESOURCE_ATTRIBUTES
        // .service.production.envs.OTEL_RESOURCE_ATTRIBUTES
      name: Read OTEL_RESOURCE_ATTRIBUTES from app.toml
      repo: ${Metadata.Name}
      rule: jsonpath
      source: github
      type: extract
    - dependsOn:
        - read-otel-resource-attributes-from-apptoml
      id: validate-otel-resource-attributes-sample-rate
      name: validate OTEL_RESOURCE_ATTRIBUTES defines sample rate
      pattern: of\.sample_rate=\d+.*
      rule: regex_match
      type: validate
    - dependsOn:
        - read-otel-resource-attributes-from-apptoml
      id: validate-otel-resource-attributes-one-sample-rate
      name: validate OTEL_RESOURCE_ATTRIBUTES defines one sample rate
      pattern: of\.error_sample_rate=\d+.*
      rule: regex_match
      type: validate
    - dependsOn:
        - validate-otel-resource-attributes-sample-rate
        - validate-otel-resource-attributes-one-sample-rate
      id: either-sample-rate-or-error-sample-rate
      method: or
      name: Validate that OTEL_RESOURCE_ATTRIBUTES contains either of.sample_rate or of.error_sample_rate
      type: aggregate
    - dependsOn:
        - validate-otel-service-name-matches-component-name
        - validate-otel-resource-attributes-one-sample-rate
      id: aggregate-otel-checks
      method: and
      name: Validate that both OTEL_SERVICE_NAME and OTEL_RESOURCE_ATTRIBUTES are set
        up correctly
      type: aggregate
  grading-system: observability
  componentType:
    - service
    - cloud-resource