apiVersion: catalog.onefootball.com/v1alpha1
kind: Metric
metadata:
  name: security-as-pipeline
spec:
  description: https://github.com/motain/of-catalog/blob/main/docs/grading-system/security.md#security-as-pipeline
  format:
    unit: Security as Pipeline
  name: security-as-pipeline
  facts:
  - id: trivy-exists-in-ci
    name: Check if Trivy is used in CI/CD pipeline
    repo: ${Metadata.Name}
    rule: search
    searchString: motain/onefootball-actions/security
    source: github
    type: extract
  componentType:
    - service
    - cloud-resource
  grading-system: security
  evaluateOnDeploy: true
  cronSchedule: "0 * * * *"