{{- if .Values.rbac.create -}}
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRoleBinding
metadata:
  name: {{ include "catalog-controller.fullname" . }}
  labels:
    {{- include "catalog-controller.labels" . | nindent 4 }}
subjects:
- kind: ServiceAccount
  name: {{ include "catalog-controller.serviceAccountName" . }}
  namespace: {{ .Values.namespace }}
roleRef:
  kind: ClusterRole
  name: {{ include "catalog-controller.fullname" . }}
  apiGroup: rbac.authorization.k8s.io
{{- end }}