{{- if and .Values.compass.credentials.create (not .Values.compass.credentials.existingSecret) }}
apiVersion: v1
kind: Secret
metadata:
  name: {{ include "catalog-controller.secretName" . }}
  namespace: {{ .Values.namespace }}
  labels:
    {{- include "catalog-controller.labels" . | nindent 4 }}
type: Opaque
data:
  cloud-id: {{ .Values.compass.credentials.cloudId | b64enc | quote }}
  api-token: {{ .Values.compass.credentials.apiToken | b64enc | quote }}
{{- end }}