replicaCount: 1

image:
  repository: catalog-controller
  pullPolicy: Always
  tag: latest

nameOverride: ""
fullnameOverride: ""

serviceAccount:
  create: true
  name: ""

rbac:
  create: true

resources:
  requests:
    cpu: 100m
    memory: 128Mi
  limits:
    cpu: 200m
    memory: 256Mi

autoscaling:
  enabled: true
  minReplicas: 3
  maxReplicas: 5
  targetCPUUtilizationPercentage: 80
  targetMemoryUtilizationPercentage: 80

controllers:
  - resource: "components"
    resyncPeriod: "5m"
    service:  catalog-controller.catalog-controller.svc.cluster.local
    sync:
      path: "/sync/components"
      timeout: "15m"
    finalizer:
      path: "/finalize/components"
      timeout: "15m"
  - resource: "scorecards"
    resyncPeriod: "5m"
    service: catalog-controller.catalog-controller.svc.cluster.local
    sync:
      path: "/sync/scorecards"
      timeout: "15m"
    finalizer:
      path: "/finalize/scorecards"
      timeout: "15m"
  - resource: "metrics"
    resyncPeriod: "5m"
    service: catalog-controller.catalog-controller.svc.cluster.local
    sync:
      path: "/sync/metrics"
      timeout: "15m"
    finalizer:
      path: "/finalize/metrics"
      timeout: "15m"
    children:
      - apiVersion: batch/v1
        resource: cronjobs

env:
  - name: COMPASS_SERVICE
    value: compass-service.compass-service.svc.cluster.local
  - name: METRIC_EVALUATION_SERVICE
    value: metric-evaluation-service.compass.svc.cluster.local