nameOverride: ""
fullnameOverride: ""

serviceAccount:
  create: true
  annotations: {}
  name: ""

image:
  repository: 706922411989.dkr.ecr.eu-west-1.amazonaws.com/catalog-controller
  pullPolicy: Always
  tag: latest

service:
  type: ClusterIP
  port: 80

containerPort: 7070

resources: {}

autoscaling:
  enabled: false

probes:
  liveness:
    path: /healthz
    initialDelaySeconds: 10
    periodSeconds: 30
  readiness:
    path: /healthz
    initialDelaySeconds: 5
    periodSeconds: 10

resyncPeriodSeconds: &resyncPeriodSeconds 600
timeoutSeconds: &timeoutSeconds "600s"

controllers:
  - resource: "components"
    resyncPeriod: *resyncPeriodSeconds
    service: catalog-controller.catalog-controller.svc.cluster.local
    sync:
      path: "/sync/component"
      timeout: *timeoutSeconds
    finalizer:
      path: "/finalize/component"
      timeout: *timeoutSeconds
  - resource: "scorecards"
    resyncPeriod: *resyncPeriodSeconds
    service: catalog-controller.catalog-controller.svc.cluster.local
    sync:
      path: "/sync/scorecard"
      timeout: *timeoutSeconds
    finalizer:
      path: "/finalize/scorecard"
      timeout: *timeoutSeconds
#  - resource: "metrics"
#    resyncPeriod: *resyncPeriodSeconds
#    service: catalog-controller.catalog-controller.svc.cluster.local
#    sync:
#      path: "/sync/metric"
#      timeout: *timeoutSeconds
#    finalizer:
#      path: "/finalize/metric"
#      timeout: *timeoutSeconds
#    children:
#      - apiVersion: batch/v1
#        resource: cronjobs

env: []

affinity: {}

topologySpreadConstraints: []

tolerations: []

nodeSelector: {}
