nameOverride: ""
fullnameOverride: ""

serviceAccount:
  create: true
  annotations: {}
  name: ""

image:
  repository: 706922411989.dkr.ecr.eu-west-1.amazonaws.com/catalog-controller
  pullPolicy: Always
  tag: latest

service:
  type: ClusterIP
  port: 80

containerPort: 7070

resources: {}

autoscaling:
  enabled: false

probes:
  liveness:
    path: /healthz
    initialDelaySeconds: 10
    periodSeconds: 30
  readiness:
    path: /healthz
    initialDelaySeconds: 5
    periodSeconds: 10

controllers: []

env: []

affinity: {}

topologySpreadConstraints: []

tolerations: []

nodeSelector: {}
