
name: Deployment Pipeline

on:
  push:
    branches:
      - main
    paths-ignore:
      - 'charts/**'
      - '.github/**'
      - 'docs/**'
      - '*.md'

permissions: write-all

jobs:
  release:
    runs-on: ubuntu-latest
    timeout-minutes: 5
    steps:
      - uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - name: Set up python
        id: setup-python
        uses: actions/setup-python@v5
        with:
          python-version: '3.12'

      - name: Generate Version
        id: version
        uses: motain/onefootball-actions/bump-release@master
        with:
          access_token: ${{ github.token }}
          repository: ${{ github.repository }}
          tag_only: true

      - id: build-release-candidate
        uses: motain/onefootball-actions/docker-build-push@master
        with:
          push: True
          tag: ${{ steps.version.outputs.new-version}}
          latest: true

      - id: security-checks
        uses: motain/onefootball-actions/security@master
        with:
          token: ${{ github.token }}
          path: "."
          image-url: ${{ steps.build-release-candidate.outputs.image-url }}

      - name: Delete Tag
        if: failure()
        run: |
          git tag -d ${{ steps.version.outputs.new-version }}
          git push origin :refs/tags/${{ steps.version.outputs.new-version }}
          echo "Tag deleted"

      - name: Release
        uses: softprops/action-gh-release@v2
        with:
          name: ${{ steps.version.outputs.new-version }}
          tag_name: ${{ steps.version.outputs.new-version }}
          generate_release_notes: true
          make_latest: true