apiVersion: batch/v1
kind: CronJob
metadata:
  annotations:
    {% for key, value in annotations.items() %}
    {{ key }}: "{{ value }}"
    {% endfor %}
  labels:
    {% for key, value in labels.items() %}
    {{ key }}: "{{ value }}"
    {% endfor %}
  name: "{{ name }}"
  namespace: "catalog-controller"
spec:
  concurrencyPolicy: Forbid
  failedJobsHistoryLimit: 2
  schedule: "{{ schedule }}"
  successfulJobsHistoryLimit: 1
  jobTemplate:
    metadata:
      labels:
        {% for key, value in labels.items() %}
        {{ key }}: "{{ value }}"
        {% endfor %}
    spec:
      template:
        metadata:
          labels:
            {% for key, value in labels.items() %}
            {{ key }}: "{{ value }}"
            {% endfor %}
        spec:
          containers:
          - name: compute-caller
            image: alpine/curl
            imagePullPolicy: Always
            command:
            - /bin/sh
            - -c
            - "{{ command }}"
            resources: {}
            terminationMessagePolicy: File
          restartPolicy: Never
          nodeSelector:
            nodegroup.onefootball.com/class: "platform"
          tolerations:
            - key: "nodegroup.onefootball.com/platform"
              operator: "Exists"
              effect: "NoSchedule"
          affinity:
            podAntiAffinity:
              preferredDuringSchedulingIgnoredDuringExecution:
                - weight: 100
                  podAffinityTerm:
                    labelSelector:
                      matchExpressions:
                        - key: app.kubernetes.io/name
                          operator: In
                          values:
                            - emissary-private
                    topologyKey: kubernetes.io/hostname