apiVersion: batch/v1
kind: CronJob
metadata:
  annotations: "ANNOTATIONS"
  labels: "ANNOTATIONS"
  name: "NAME"
  namespace: "catalog-controller"
spec:
  concurrencyPolicy: Forbid
  failedJobsHistoryLimit: 2
  jobTemplate:
    metadata:
      labels: "LABELS"
    spec:
      template:
        metadata:
          labels: "LABELS"
        spec:
          containers:
          - command:
            - /bin/sh
            - -c
            - "CURL_COMMAND"
            image: alpine/curl
            imagePullPolicy: Always
            name: compute-caller
            resources: {}
            terminationMessagePath: /dev/termination-log
            terminationMessagePolicy: File
          dnsPolicy: ClusterFirst
          restartPolicy: Never
          schedulerName: default-scheduler
          securityContext: {}
          terminationGracePeriodSeconds: 30
          nodeSelector:
            nodegroup.onefootball.com/class: "platform"
          tolerations:
            - key: "nodegroup.onefootball.com/platform"
              operator: "Exists"
              effect: "NoSchedule"
          affinity:
            podAntiAffinity:
              preferredDuringSchedulingIgnoredDuringExecution:
                - podAffinityTerm:
                    labelSelector:
                      matchExpressions:
                        - key: app.kubernetes.io/name
                          operator: In
                          values:
                            - emissary-private
                    topologyKey: kubernetes.io/hostname
                  weight: 100
  schedule: "cronSchedule"
  successfulJobsHistoryLimit: 1